export const GET_BALANCE_REQUEST = 'GET_BALANCE_REQUEST';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'GET_BALANCE_FAILURE';

export const ADD_BALANCE_REQUEST = 'ADD_BALANCE_REQUEST';
export const ADD_BALANCE_SUCCESS = 'ADD_BALANCE_SUCCESS';
export const ADD_BALANCE_FAILURE = 'ADD_BALANCE_FAILURE';

export const TRANSFER_BALANCE_REQUEST = 'TRANSFER_BALANCE_REQUEST';
export const TRANSFER_BALANCE_SUCCESS = 'TRANSFER_BALANCE_SUCCESS';
export const TRANSFER_BALANCE_FAILURE = 'TRANSFER_BALANCE_FAILURE';
